version: '3'

services:

  server:
    image: nginx:alpine
    container_name: fm-server
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./server/nginx-conf:/etc/nginx/conf.d
    networks:
      - app-network
    links:
      - app

  app:
    build: ./app/
    image: fm-app
    container_name: fm-app
    restart: always
    ports:
      - "9000"
    volumes:
      - ./app:/var/www
      - vendor:/var/www/vendor
    networks:
      - app-network
    depends_on:
      - db

  db:
    image: mariadb:latest
    container_name: fm-db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: fm_db
      MYSQL_USER: user
      MYSQL_PASSWORD: user_pwd
    ports:
      - "27017:27017"
    volumes:
      - dbdata:/data/db
      - ./db/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    networks:
      - app-network

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080
    networks:
      - app-network
    depends_on:
      - db

networks:
  app-network:
    driver: bridge

volumes:
  dbdata:
  vendor: